# Generated by cucumber-sinatra. (2013-11-30 18:12:32 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/pokrovsky.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'timecop'

require 'coveralls'
Coveralls.wear!

Capybara.app = PokrovskyService

class PokrovskyServiceWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  PokrovskyServiceWorld.new
end
